### PR TITLE
New Example: search.py

### PR DESCRIPTION
**Pull request by antoninoLorenzo**
Hi, I am using your project and I wanted to contribute to it, so I added an example that shows how search works to help other users understand the package.

I also would consider adding all the examples in the documentation.

### CODE REVIEW

**Comment by wchistow** [comment]
Thanks!

**Comment by wchistow** [comment]
I've added all examples to documentation.

**Comment by antoninoLorenzo** [comment]
Great, it will be easier to understand how to work, with the library.

However I am working on a `Questions` class that serves as interface for the results of `Site.search()` and make it easier to work with results (sort, filter etc.); I am making it for my project, but if you are conseidering expanding the library with other features let me know.

**Comment by Peter-developer01** [comment]
@antoninoLorenzo thanks for your contribution to PyStackAPI!

**Pull request merged**
